fiaas/skipper

.dockerignore
Dockerfile
setup.py

The setup here is really quite simple:
* First we create a stage named `common`, where we install anything that is needed both while building and at runtime. In our case, it's just libyaml.
* Second, we create a stage named `build`, based on `common`. Here we install build-tools, needed headers etc. Then we build binary wheels of all our dependencies and our application.
* Last, we create a stage named `production`, based on `common` again. This gets rid of all the tools and stuff needed to build the binaries. We then copy the binary wheels from `build` and use those to install the application.

Use multi-stage build for Docker

---

fiaas_skipper/__init__.py
fiaas_skipper/config.py
fiaas_skipper/deploy/crd/deployer.py
fiaas_skipper/deploy/deploy.py
fiaas_skipper/deploy/tpr/deployer.py
helm/fiaas-skipper/Chart.yaml
helm/fiaas-skipper/templates/config_map.yaml
helm/fiaas-skipper/templates/deployment.yaml
helm/fiaas-skipper/templates/ingress.yaml
helm/fiaas-skipper/values.yaml
tests/fiaas_skipper/web/test_api.py

Cleaned up the chart a bit.
I realized that the only reason skipper needs an ingress-suffix configured is because it uses it to generate `host` values in the created TPR/CRD objects for fiaas-deploy-daemon. We don't really care about the web-interface of fiaas-deploy-daemon, especially not from outside the cluster, so if the ingress points to a randomly selected fiaas-deploy-daemon, it's not really a big problem. We have plans to make ingress per namespace work as expected, and once we do, this will be solved. Until then, we don't really need it. Once we come to that conclusion, we can just remove all the code that has to to with passing ingress-suffix around, making the chart simpler in the process.
Worth noticing: Only a single test failed/needed to be changed to handle the sweeping …

Clean up chart, and remove some unneeded/unwanted options

---

fiaas_skipper/deploy/deploy.py

This can happen as deployments are taking place and pods are being
replaced.

Handle availableReplicas being absent from status

---

fiaas_skipper/deploy/crd/deployer.py
fiaas_skipper/deploy/tpr/deployer.py
tests/fiaas_skipper/deploy/crd/test_deployer.py
tests/fiaas_skipper/deploy/tpr/test_deployer.py

When there are pre-existing resources already in place they need to be updated
through get_or_create where the existing instance is updated and saved.
Previously this case wasn't covered leaving any existing application specs intact.

Fix deployment of applications

---

helm/fiaas-skipper/fiaas.yaml

This adds annotations for log-aggregation and correct endpoint for scraping prometheus metrics for fiaas-deploy-daemon.

Extend fiaas-deploy-daemon spec file

---

fiaas_skipper/web/templates/status.html
helm/fiaas-skipper/templates/deployment.yaml

Reducing ui status refresh rate and increasing liveness probe timeout value as
getting the status across the cluster can be a timeconsuming operation.

Adjust liveness probe to accomodate for potential slow responses

---

fiaas_skipper/deploy/bootstrap.py
fiaas_skipper/deploy/crd/bootstrap.py
fiaas_skipper/deploy/tpr/bootstrap.py
helm/fiaas-skipper/templates/config_map.yaml

In order to avoid problems with batch jobs without backoff policies on 1.6 perhaps this could be explored as an alternative approach. This would potentially requires additionally cleaning up bootstrapping pods.

Switch to bare pod bootstrapper

---

fiaas_skipper/__init__.py
fiaas_skipper/deploy/__init__.py
fiaas_skipper/deploy/cluster.py
fiaas_skipper/deploy/deploy.py
fiaas_skipper/web/api.py
tests/fiaas_skipper/deploy/crd/test_deployer.py
tests/fiaas_skipper/deploy/test_cluster.py
tests/fiaas_skipper/deploy/test_deploy.py
tests/fiaas_skipper/deploy/tpr/test_deployer.py
tests/fiaas_skipper/web/test_api.py

Hopefully making the code a bit more efficient and readable. We now fetch all deployments matching the wanted name, instead of fetching them one by one. This should be significantly faster.

Refactor some code around deployment config and status

---

.gitignore
fiaas_skipper/deploy/bootstrap.py
setup.cfg
tests/fiaas_skipper/conftest.py
tests/fiaas_skipper/deploy/test_bootstrap.py

We were relying on the default resource requests/limits enforced by the limitrange in most namespaces, which worked by coincidence untill we hit a namespace that didn't have defaults but did have a resourcequota denying pods with BestEffort QoS. This caused the bootstrapping pod to not be scheduled. Now skipper will use there resources specified in fiaas-deploy-daemon's fiaas.yml when creating the bootstrapping pod as well, unless there is a resourcequota enforcing BestEffort QoS pods only.

DOCD-1685 Set resource requests/limits from fiaas.yml on bootstrapping pod

---

fiaas_skipper/web/__init__.py
fiaas_skipper/web/static/skipper.js
fiaas_skipper/web/templates/deploy.html
fiaas_skipper/web/templates/status.html

There were some stray inline scripts and css that were prevented from running which have now been extracted to external js files that allow them to be run. The csp policy was adjusted to include settings that were missing. Added on page load mechanism to execute selective document ready blocks previously included on each template.

 Adjust content security policy and get rid of inline scripts/css

---

fiaas_skipper/__init__.py
fiaas_skipper/config.py
fiaas_skipper/deploy/cluster.py
fiaas_skipper/deploy/crd/deployer.py
fiaas_skipper/deploy/crd/types.py
fiaas_skipper/deploy/deploy.py
fiaas_skipper/deploy/tpr/deployer.py
fiaas_skipper/deploy/tpr/types.py
fiaas_skipper/update.py
fiaas_skipper/web/api.py
fiaas_skipper/web/static/skipper.js
fiaas_skipper/web/templates/status.html
tests/fiaas_skipper/deploy/test_cluster.py
tests/fiaas_skipper/deploy/test_deploy.py
tests/fiaas_skipper/test_update.py
tests/fiaas_skipper/web/test_api.py

This adds functionality for auto updating fiaas-deploy-daemon when new versions become available.
Each namespace is inspected to see if it matches the current version and updated as needed.
Deployment statuses have been extended to detect version mismatch and application missing.

Auto-update when new versions are available

---

fiaas_skipper/deploy/deploy.py
fiaas_skipper/web/api.py
fiaas_skipper/web/static/skipper.js
fiaas_skipper/web/templates/status.html
setup.py
tests/fiaas_skipper/deploy/test_deploy.py
tests/fiaas_skipper/web/test_api.py

This extends the deploy endpoint to accept a flag for forcing bootstrap of namespaces with fiaas-deploy-daemon.
Web UI has also been extended to display a modal dialog with a force-bootstrap checkbox when deploying.
Additionally this bumps the flask version to 1.x and pins the flask bootstrap version to avoid possible issues with future versions.

Support forcing bootstrapping of namespaces

---

fiaas_skipper/__init__.py
fiaas_skipper/config.py
fiaas_skipper/deploy/deploy.py
helm/fiaas-skipper/templates/config_map.yaml
helm/fiaas-skipper/values.yaml
tests/fiaas_skipper/deploy/test_deploy.py

The default should be low but allow for specifing a less frequent interval
when multiple namespaces are configured where checking status could
be expensive.

Allow configuring interval for checking status of namespaces

---

.codacy.yml

As can be seen in #59, when Codacy analyses the codebase, it seems to be running Prospector using Python 2. According to Codacy support, adding a configuration like this might solve the problem. They pointed to documentation that indicated it would only work for pylint, but I explicitly asked about Prospector, so there is a chance the documentation is outdated.
Giving it a go anyways.

Adding codacy config to make prospector use Python 3

---

fiaas_skipper/deploy/channel.py
fiaas_skipper/web/frontend.py
tests/fiaas_skipper/deploy/test_channel.py

This can happen if an operator would specify an invalid baseurl where
release metadata can be found.

Avoid throwing exception when trying to determine versions

---

fiaas_skipper/update.py
tests/fiaas_skipper/test_update.py

This will make sure that Skipper automatically forces bootstrap if fiaas-deploy-daemon doesn't update itself in a timely manner.

Force bootstrap on deployment not found or version mismatch

---

README.md
helm/fiaas-skipper/templates/fiaas-deploy-daemon-configmap.yaml
helm/fiaas-skipper/values.yaml

If the flag is set this will bootstrap the daemon when skipper is installed, in the
same namespace. This is useful for first time users or in a simple setup where there is only one namespace. The fiaas-deploy-daemon configmap can then of course be updated afterwards but the fiaas-deploy-daemon would have been bootstrapped already.

Add flag for installing fiaas-deploy-daemon configmap when installing fiaas-skipper

---

.travis.yml
bin/docker_push
bin/publish_helm_chart

This updates the helm/fiaas-skipper/values.yaml file in place with
version reference for the image.tag before packaging the helm chart.
This will ensure that the helm chart that will be published contains a
reference to the docker image tag with the version reference instead of
relying on latest.

Explicitly set docker image tag in helm chart

---

.travis.yml
bin/publish_helm_chart
bin/tag_release

This introduces automatic tagging with semver on merges to master which
will generate releases based on pre-existings tags. The utility used
will automatically increment the patch version of the last tag: v0.0.1
to v0.0.2 or v0.1.0 to v.0.1.1.
The semver tag will be used to augment the helm chart version as well to
match the tag (excluding the v prefix) for better tracability.
When a tag has been pushed a release is created and docker image and
helm chart published.

Tag releases and publish on release

---

helm/fiaas-skipper/templates/deployment.yaml

Add checksum of fiaas_override.yaml as an annotation to the pod template, similar to the way config_map.yaml is handled.

Roll pods if fiaas_override is modified

---

helm/fiaas-skipper/templates/fiaas-deploy-daemon-configmap.yaml
helm/fiaas-skipper/values.yaml

Skipper needs this to determine which version of fiaas-deploy-daemon to deploy

Set tag in fiaas-deploy-daemon configmap

---

helm/fiaas-skipper/templates/config_map.yaml
helm/fiaas-skipper/values.yaml

fiaas_override_yaml is now a string(scalar) value that can be used to override
configuration in the fiaas.yml used to deploy fiaas-deploy-daemon.
example:
```
$ helm upgrade --namespace fiaas --install "fiaas-skipper" "fiaas-skipper" --repo https://fiaas.github.io/helm --set "fiaas_override_yaml=
annotations:
ingress:
\"nginx\.ingress\.kubernetes\.io/whitelist-source-range\": \"10.0.0.0/8\""
```
When `fiaas_override_yaml` is not set, we're falling back to the current behavior of using the `fiaas_override.yaml` file

Make it possible to override fiaas_override.yaml

---

helm/fiaas-skipper/values.yaml

The release channel metadata has been moved to github and is now available through github pages https://fiaas.github.io/releases/

Update release channel url

---

.gitignore
Dockerfile
bin/docker_build

Some of our dependencies does not have pre-built wheels on PyPI, and can take a while to build. At the same time, since we are building inside docker, we don't get the benefit of the pip cache available in Travis.
These changes will inject the wheels in the pip cache into the docker context, and then use them when building. In order for the cache to have any value, we need to take the wheels we do build out of the image and put them into the pip cache again. This is done by "saving" the image to a temporary directory, then searching the layers for files matching the pattern `/wheels/*.whl`, and stuffing them into the pip cache.
Unfortunately, pip uses a naming scheme that isn't documented, so we can't actually put the wheels in the proper place in the cache. That doesn't matter though, as …

Cache wheels between docker builds to speed up building

---

helm/fiaas-skipper/templates/fiaas-deploy-daemon-configmap.yaml
helm/fiaas-skipper/values.yaml

Add a value to the helm chart which can be used to configure fiaas-deploy-daemon configmaps in different user-specified namespaces. 
I'm not sure if it makes sense (or how) to deprecate or remove `addFiaasDeployDaemonConfigmap` at the same time.
This should solve #89

Support configuring fiaas-deploy-daemon configmaps in multiple namespaces

---

helm/fiaas-skipper/templates/deployment.yaml

See: https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

Remove deprecated APIs removed in 1.16

---

.prospector.yaml
helm/fiaas-skipper/templates/rbac.yaml

The latest change in fiaas-deploy-daemon that added support for multiple ingresses uses deletecollection to clean-up

Add deletecollection to ClusterRole

---

helm/fiaas-skipper/templates/fiaas-deploy-daemon-configmap.yaml

This fixes a nil reference issue with template rendering when the
`fiaasDeployDaemonConfigMaps` value is used to configure the content of
fiaas-deploy-daemon configmaps.
When changing scope in a template (with range in this case) it is no
longer possible to refer directly to e.g. `.Values.foo`. To refer to a value in
the root scope, we have to use `$.Values.foo`.

Use $ to get root scope when rendering configmap

---

helm/fiaas-skipper/templates/ingress.yaml
helm/fiaas-skipper/values.yaml

This PR will add TLS related annotations to the ingress if `enableTLS` flag is set to true.
This will make this chart closer to the `Mast` chart where this sort of behaviour is used.

Add TLS annotations in ingress if TLS is enabled

---

.travis.yml
helm/fiaas-skipper/templates/ingress.yaml
helm/fiaas-skipper/values.yaml

Since [v0.11.0](https://github.com/jetstack/cert-manager/releases/tag/v0.11.0) that the annotation with `certmanager.k8s.io` have been renamed to `cert-manager.io`.
So this PR upgrades the skipper helm chart to match that.

[Cert-manager] Update cert-manager annotations

---

bin/docker_build
bin/docker_push

Disabling ARM builds for now due to taking a long time and making the CI job take too long and being terminated by Travis.
When executing https://github.com/fiaas/skipper/issues/107, it should be perfectly fine to re-enable multi-arch builds

Temporarily disable ARM builds

---

.travis.yml
bin/publish_helm_chart

The last build on [master](https://travis-ci.org/github/fiaas/skipper/builds/772735920) failed - this time because the helm version is very old and the build-in repos are not available anymore.
The easiest fix would have been to upgrade to the last version of helm v2.X - but helm 2.x is discontinued in favour of helm 3.
I've noticed that in helm 3, `helm init` is not used anymore - from a quick glance, I think the rest of the helm commands are the same in helm v2 and v3 🤞 but I was not able to test it.

Fix helm packaging - upgrade to latest version

---

README.md
helm/fiaas-skipper/values.yaml

I think `autoUpdate` is something most setups of skipper probably don't want enabled, so I think it would be a good idea for that flag to default to false. Any thoughts on this change in default values?
I've made an attempt at improving the parts of the readme covering how skipper works, and also added some documentation about how the latest and stable tags work. (I originally just wanted to make the documentation a bit clearer, but as I got to the part covering automatic updates, I started thinking it might be best if that feature was disabled by default too).

Disable autoUpdate by default, improve documentation

---

helm/fiaas-skipper/Chart.yaml
helm/fiaas-skipper/templates/deployment.yaml
helm/fiaas-skipper/templates/rbac.yaml

give skipper its own service account
currently skipper is using the default service account. Since it makes calls to the apiserver, it should be identifying itself using serviceaccounts. This PR modifies the helm chart to assign a serviceaccount to the skipper pod as well as a clusterrolebinding which assigns the fiaas-control clusterrole to the skipper serviceaccount in an explicit manner.
This PR is the first step in moving towards more explicit RBAC control over FIAAS apps. Next steps will include ceasing the practice of assinging the fiaas-controler clusterrole to every service account in every namespace.

give skipper its own service account

---

.semaphore/semaphore.yml
bin/docker_build

The docker build --output flag seems not to save the json metadata for the image, therefore when we attempted to run the container it failed because the Cmd field was not set.

Use docker save to store the container

---

bin/deploy

The version generated by setup.py includes a timestamp, so multiple calls will produce different output. Get the version string once and use the same value where needed.
This should fix an issue with the helm chart pointing to a docker image tag which doesn't exist in the latest version of the chart.

Use consistent skipper version during deploy

---

fiaas_skipper/__init__.py

Fixes #103
This is untested, in the sense that I haven't tested skipper with these changes, but I have done this in other applications running on kubernetes, and it behaves as you would expect.
Obviously, this would be a bad idea if the application needs to perform some cleanup on SIGTERM/SIGINT, but I'm fairly sure skipper doesn't need that (and if so, it isn't doing it as it is).

Handle SIGTERM and SIGINT gracefully

---

fiaas_skipper/deploy/rbac.py
helm/fiaas-skipper/templates/rbac.yaml

`role` and `rolebindings` permissions are needed because of this: https://github.com/fiaas/skipper/blob/PerGon-patch-1/fiaas_skipper/deploy/rbac.py#L41-L49

Some fixes around RBAC

---

fiaas_skipper/deploy/bootstrap.py
fiaas_skipper/deploy/cluster.py
tests/fiaas_skipper/deploy/crd/test_deployer.py
tests/fiaas_skipper/deploy/test_bootstrap.py
tests/fiaas_skipper/deploy/test_cluster.py
tests/fiaas_skipper/deploy/test_deploy.py

the bootstrap pod, when deployed by skipper, doesn't currently heed the enable-service-account-per-app field in the FDD configmap. This behaviour is implemented by this PR.

conditionally enable service-account-per-app in bootstrap pod

---

fiaas_skipper/web/static/skipper.js

Fixes #126.
I think this is a regression after #117 changed the content-type of
/api/status to return application/json. The client side (js) treats the
response from /api/status as a string containing json because the content
type used to be text/html (which was also wrong), but now it gets json
. When the client tries to parse the response, parseJSON raises a
exception because the response is already json. 
Skip the parsing and just use the response object directly as it is json.

Fix status view; /api/status returns json, don't parse it

---

fiaas_skipper/__init__.py
fiaas_skipper/config.py
setup.py

Use built-in support in fiaas/k8s for in-cluster config for the Kubernetes client. This  regularly refreshes the service account token from disk, which is needed for running on Kubernetes 1.21+ with BoundServiceAccountTokenVolume and time-bound tokens. The behavior should be the same as implemented for fiaas-deploy-daemon implemented in https://github.com/fiaas/fiaas-deploy-daemon/pull/166.
closes: #127

Use built-in support for k8s client in-cluster config

---

helm/fiaas-skipper/templates/ingress.yaml
helm/fiaas-skipper/values.yaml

the ingress deployed in skipper's helm chart for accessing its web interface is deployed using the extensions/v1beta1 api. The networking.k8s.io/v1 api should be optionally used for this purpose.

allow networking/v1 ingress in chart

---

helm/fiaas-skipper/templates/rbac.yaml

When installing this chart on GKE, ClusterRole and ClusterRoleBindings are always installed using the rbac.authorization.k8s.io/v1beta1 API version. This seems to happen because the conditional which checks Kubernetes version with `semverCompare` always renders as false in GKE because the Kubernetes version in GKE is usually major.minor.patch-gke.release (e.g. 1.20.12-gke.1500). `semverCompare` apparently can't compare that version pattern.
rbac.authorization.k8s.io/v1beta1 is removed in Kubernetes 1.22, so the chart must be fixed to install cleanly on GKE 1.22+. Rather than trying to fix the conditional I think it should be fine to always use rbac.authorization.k8s.io/v1, as this API version is available since Kubernetes 1.8.
This means the next release of the skipper chart will not …

Always use v1 RBAC API for clusterrole + clusterrolebindings (drops compatibility with Kubernetes 1.7 and earlier)

---

.prospector.yaml
helm/fiaas-skipper/templates/rbac.yaml
helm/fiaas-skipper/values.yaml

Skipper's Helm chart still includes an RBAC clusterRole/clusterRoleBinding which gives huge permissions to all service accounts in the cluster. Thus any pod with a serviceAccountToken is able to perform almost unlimited read/write calls to the Kubernetes API. This PR allows one to turn this off in the Helm chart.

allow opting out from fiaas-controller role

---

helm/fiaas-skipper/templates/rbac.yaml
helm/fiaas-skipper/values.yaml

We recently discovered that fiaas-deploy-daemon is missing cluster wide permissions to get/create/update our CRD's, something it does on startup. This necessitates a clusterrole since CRD's are scoped at the cluster level. It would be a lot of work to implement this in Skipper's code, especially considering that the models would also need to be implemented in the k8s library. Therefore a simple addition to the helm chart is what we've included here, with a list of namespaces in which the clusterrole should be bound to fiaas-deploy-daemon serviceAccounts.

create fdd clusterrole for crd creation/updating

---

setup.py

setuptools_scm 7.0.0 and later do not support python 3.6, which makes the CI build fail with a SyntaxError. Pin setuptools_scm to the latest 6.x release.

Fix CI build issue with setuptools_scm 7.x

---

.semaphore/semaphore.yml
bin/deploy
tox.ini

Need to get a helm chart update pushed. Having issues with outdated packages and to get the chart out I'm disabling running tests and building the docker image temporarily.

Temporarily disable tox and docker build
